# Generated by Django 5.1.2 on 2024-10-14 03:40

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_name', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
