# Generated by Django 5.1.2 on 2024-10-14 03:42

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='instructions',
            field=banjo.models.StringField(default=''),
        ),
    ]
