# Generated by Django 5.1.2 on 2024-10-22 11:31

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_drill_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='likes',
            field=banjo.models.StringField(default=''),
        ),
    ]
