# Generated by Django 5.1.2 on 2024-10-22 11:40

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_drill_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='likes',
            field=banjo.models.IntegerField(default=0, verbose_name=0),
        ),
    ]
