# Generated by Django 5.1.2 on 2024-10-18 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_drill_difficulty_drill_level_drill_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='difficulty',
        ),
    ]
